// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZPKFBT88a_mdJQ8sQRPXV7NWqMQ09d7c',
    appId: '1:1052552490356:web:11c4183680f5ffd5319021',
    messagingSenderId: '1052552490356',
    projectId: 'hello-chat-app-c5e04',
    authDomain: 'hello-chat-app-c5e04.firebaseapp.com',
    storageBucket: 'hello-chat-app-c5e04.appspot.com',
    measurementId: 'G-5LJQGP8VRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE_Mv3gurRxTZSTre_u7ai-C7ou8nIBwA',
    appId: '1:1052552490356:android:f38f0f108faf0f08319021',
    messagingSenderId: '1052552490356',
    projectId: 'hello-chat-app-c5e04',
    storageBucket: 'hello-chat-app-c5e04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnYKfK-3wOZ3KWJ6OdbAWJtGuULm016zk',
    appId: '1:1052552490356:ios:1b8031826ba6b349319021',
    messagingSenderId: '1052552490356',
    projectId: 'hello-chat-app-c5e04',
    storageBucket: 'hello-chat-app-c5e04.appspot.com',
    iosBundleId: 'com.example.hello',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnYKfK-3wOZ3KWJ6OdbAWJtGuULm016zk',
    appId: '1:1052552490356:ios:15ba36506222028c319021',
    messagingSenderId: '1052552490356',
    projectId: 'hello-chat-app-c5e04',
    storageBucket: 'hello-chat-app-c5e04.appspot.com',
    iosBundleId: 'com.example.hello.RunnerTests',
  );
}
